GEORGIA_OPERATOR_MAPPING = {10: 'Geocell ',
                            11: 'Magticom',
                            12: 'Veon Georgia',
                            13: 'Silknet-Fixed',
                            14: 'A-NET',
                            15: 'Georgian Telecom Company',
                            17: 'New-Net',
                            19: 'Magticom (Fixed Network)',
                            20: 'Akhteli',
                            21: 'Global One',
                            23: 'Caucasus Digital Network',
                            24: 'Caucasus Online',
                            25: 'Servicenet',
                            26: 'Geonet',
                            27: 'Good Will Com',
                            28: 'Lagi',
                            29: 'Telco Systems ',
                            31: 'Inexphone',
                            33: 'Myphone',
                            34: 'Georgian Railway',
                            39: 'CGC',
                            41: 'Silknet-Mobile',
                            42: 'Georgian Media Production Group',
                            45: 'Mobitel fixed',
                            46: 'Sky Net',
                            48: 'City Telecom',
                            49: 'GlobalCell',
                            50: '09 Tech',
                            51: 'Globalcell Fixed',
                            53: 'Kvesi Group',
                            55: 'UTS',
                            56: 'Premium Net',
                            57: 'Datacomm',
                            58: 'O&M group',
                            60: 'Voxbone',
                            61: 'New Vision',
                            62: 'Arcomm',
                            64: 'Fly TV',
                            67: 'GSI Technology',
                            70: 'VoIPhone',
                            71: 'Odrex Software',
                            73: 'Vertex',
                            75: 'Mobilive',
                            76: 'TELE1',
                            77: 'Asanet',
                            78: 'Katena',
                            79: 'Urban Phone',
                            80: 'CommuniQ',
                            81: 'Datahouse Global',
                            82: 'Black Sea Telecom',
                            83: 'Telecom 1',
                            85: 'ITS',
                            86: 'Smart signal',
                            92: 'Beka Khajishvili',
                            93: 'Servicebox',
                            94: 'System 1',
                            95: 'Eclectic',
                            96: 'United Telecom',
                            97: 'Smkgroup',
                            98: 'Geosms',
                            }
